---
id: pcrs_imagery
name: PCRS raster Imagery
version: 1
author: Jean-BaptisteC
description: |
  Plugin to use PCRS raster imagery
experimental: false

imagery:
  fr_pcrs_wms:
    name: "PCRS raster"
    type: wms
    url: "https://data.geopf.fr/wms-r/wms?LAYERS=PCRS.LAMB93&STYLES=&CRS={proj}&BBOX={bbox}&FORMAT=image/jpeg&WIDTH={width}&HEIGHT={height}&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap"
    maxZoom: 20
    attribution: "PCRS - République Française"
